# Generated by Django 5.1.2 on 2024-10-27 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='birth_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
