# Generated by Django 5.1.2 on 2024-11-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_bloodneeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=3),
        ),
    ]
